/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jfeild1337.grudgebox.entitymgr;

import java.io.Serializable;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.persistence.EntityNotFoundException;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import org.jfeild1337.grudgebox.entities.GrudgeSeverityEntity;
import org.jfeild1337.grudgebox.entitymgr.exceptions.NonexistentEntityException;
import org.jfeild1337.grudgebox.entitymgr.exceptions.PreexistingEntityException;

/**
 * JPA Controller class for allowing CRUD operations on the GrudgeSeverityEntity objects and their corresponding
 * database table.
 * Generated by Netbeans IDE
 */
public class GrudgeSeverityEntityJpaController implements Serializable {

    public GrudgeSeverityEntityJpaController(EntityManagerFactory emf) {
        this.emf = emf;
    }
    private EntityManagerFactory emf = null;

    public EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    public void create(GrudgeSeverityEntity grudgeSeverityEntity) throws PreexistingEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            em.persist(grudgeSeverityEntity);
            em.getTransaction().commit();
        } catch (Exception ex) {
            if (findGrudgeSeverityEntity(grudgeSeverityEntity.getSeverityLevel()) != null) {
                throw new PreexistingEntityException("GrudgeSeverityEntity " + grudgeSeverityEntity + " already exists.", ex);
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void edit(GrudgeSeverityEntity grudgeSeverityEntity) throws NonexistentEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            grudgeSeverityEntity = em.merge(grudgeSeverityEntity);
            em.getTransaction().commit();
        } catch (Exception ex) {
            String msg = ex.getLocalizedMessage();
            if (msg == null || msg.length() == 0) {
                int id = grudgeSeverityEntity.getSeverityLevel();
                if (findGrudgeSeverityEntity(id) == null) {
                    throw new NonexistentEntityException("The grudgeSeverityEntity with id " + id + " no longer exists.");
                }
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void destroy(int id) throws NonexistentEntityException {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            GrudgeSeverityEntity grudgeSeverityEntity;
            try {
                grudgeSeverityEntity = em.getReference(GrudgeSeverityEntity.class, id);
                grudgeSeverityEntity.getSeverityLevel();
            } catch (EntityNotFoundException enfe) {
                throw new NonexistentEntityException("The grudgeSeverityEntity with id " + id + " no longer exists.", enfe);
            }
            em.remove(grudgeSeverityEntity);
            em.getTransaction().commit();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public List<GrudgeSeverityEntity> findGrudgeSeverityEntityEntities() {
        return findGrudgeSeverityEntityEntities(true, -1, -1);
    }

    public List<GrudgeSeverityEntity> findGrudgeSeverityEntityEntities(int maxResults, int firstResult) {
        return findGrudgeSeverityEntityEntities(false, maxResults, firstResult);
    }

    private List<GrudgeSeverityEntity> findGrudgeSeverityEntityEntities(boolean all, int maxResults, int firstResult) {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            cq.select(cq.from(GrudgeSeverityEntity.class));
            Query q = em.createQuery(cq);
            if (!all) {
                q.setMaxResults(maxResults);
                q.setFirstResult(firstResult);
            }
            return q.getResultList();
        } finally {
            em.close();
        }
    }

    public GrudgeSeverityEntity findGrudgeSeverityEntity(int id) {
        EntityManager em = getEntityManager();
        try {
            return em.find(GrudgeSeverityEntity.class, id);
        } finally {
            em.close();
        }
    }

    public int getGrudgeSeverityEntityCount() {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<GrudgeSeverityEntity> rt = cq.from(GrudgeSeverityEntity.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
        } finally {
            em.close();
        }
    }
    
}
