/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jfeild1337.grudgebox.entitymgr;

import java.io.Serializable;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.persistence.EntityNotFoundException;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import org.jfeild1337.grudgebox.entities.GrudgeRecordEntity;
import org.jfeild1337.grudgebox.entitymgr.exceptions.NonexistentEntityException;
import org.jfeild1337.grudgebox.entitymgr.exceptions.PreexistingEntityException;

/**
 * JPA Controller class for allowing CRUD operations on the GrudgeRecordEntity objects and their corresponding
 * database table.
 * Generated by Netbeans IDE
 */
public class GrudgeRecordEntityJpaController implements Serializable {

    public GrudgeRecordEntityJpaController(EntityManagerFactory emf) {
        this.emf = emf;
    }
    private EntityManagerFactory emf = null;

    public EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    public void create(GrudgeRecordEntity grudgeRecordEntity) throws PreexistingEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            em.persist(grudgeRecordEntity);
            em.getTransaction().commit();
        } catch (Exception ex) {
            if (findGrudgeRecordEntity(grudgeRecordEntity.getRecordId()) != null) {
                throw new PreexistingEntityException("GrudgeRecordEntity " + grudgeRecordEntity + " already exists.", ex);
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void edit(GrudgeRecordEntity grudgeRecordEntity) throws NonexistentEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            grudgeRecordEntity = em.merge(grudgeRecordEntity);
            em.getTransaction().commit();
        } catch (Exception ex) {
            String msg = ex.getLocalizedMessage();
            if (msg == null || msg.length() == 0) {
                int id = grudgeRecordEntity.getRecordId();
                if (findGrudgeRecordEntity(id) == null) {
                    throw new NonexistentEntityException("The grudgeRecordEntity with id " + id + " no longer exists.");
                }
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void destroy(int id) throws NonexistentEntityException {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            GrudgeRecordEntity grudgeRecordEntity;
            try {
                grudgeRecordEntity = em.getReference(GrudgeRecordEntity.class, id);
                grudgeRecordEntity.getRecordId();
            } catch (EntityNotFoundException enfe) {
                throw new NonexistentEntityException("The grudgeRecordEntity with id " + id + " no longer exists.", enfe);
            }
            em.remove(grudgeRecordEntity);
            em.getTransaction().commit();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public List<GrudgeRecordEntity> findGrudgeRecordEntityEntities() {
        return findGrudgeRecordEntityEntities(true, -1, -1);
    }

    public List<GrudgeRecordEntity> findGrudgeRecordEntityEntities(int maxResults, int firstResult) {
        return findGrudgeRecordEntityEntities(false, maxResults, firstResult);
    }

    private List<GrudgeRecordEntity> findGrudgeRecordEntityEntities(boolean all, int maxResults, int firstResult) {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            cq.select(cq.from(GrudgeRecordEntity.class));
            Query q = em.createQuery(cq);
            if (!all) {
                q.setMaxResults(maxResults);
                q.setFirstResult(firstResult);
            }
            return q.getResultList();
        } finally {
            em.close();
        }
    }

    public GrudgeRecordEntity findGrudgeRecordEntity(int id) {
        EntityManager em = getEntityManager();
        try {
            return em.find(GrudgeRecordEntity.class, id);
        } finally {
            em.close();
        }
    }

    public int getGrudgeRecordEntityCount() {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<GrudgeRecordEntity> rt = cq.from(GrudgeRecordEntity.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
        } finally {
            em.close();
        }
    }
    
}
