/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jfeild1337.grudgebox.entitymgr;

import java.io.Serializable;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Query;
import javax.persistence.EntityNotFoundException;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import org.jfeild1337.grudgebox.entities.SubjectsEntity;
import org.jfeild1337.grudgebox.entitymgr.exceptions.NonexistentEntityException;
import org.jfeild1337.grudgebox.entitymgr.exceptions.PreexistingEntityException;

/**
 * JPA Controller class for allowing CRUD operations on the SubjectsEntity objects and their corresponding
 * database table.
 * Generated by Netbeans IDE
 */
public class SubjectsEntityJpaController implements Serializable {

    public SubjectsEntityJpaController(EntityManagerFactory emf) {
        this.emf = emf;
    }
    private EntityManagerFactory emf = null;

    public EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    public void create(SubjectsEntity subjectsEntity) throws PreexistingEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            em.persist(subjectsEntity);
            em.getTransaction().commit();
        } catch (Exception ex) {
            if (findSubjectsEntity(subjectsEntity.getSubjectId()) != null) {
                throw new PreexistingEntityException("SubjectsEntity " + subjectsEntity + " already exists.", ex);
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void edit(SubjectsEntity subjectsEntity) throws NonexistentEntityException, Exception {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            subjectsEntity = em.merge(subjectsEntity);
            em.getTransaction().commit();
        } catch (Exception ex) {
            String msg = ex.getLocalizedMessage();
            if (msg == null || msg.length() == 0) {
                int id = subjectsEntity.getSubjectId();
                if (findSubjectsEntity(id) == null) {
                    throw new NonexistentEntityException("The subjectsEntity with id " + id + " no longer exists.");
                }
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void destroy(int id) throws NonexistentEntityException {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            SubjectsEntity subjectsEntity;
            try {
                subjectsEntity = em.getReference(SubjectsEntity.class, id);
                subjectsEntity.getSubjectId();
            } catch (EntityNotFoundException enfe) {
                throw new NonexistentEntityException("The subjectsEntity with id " + id + " no longer exists.", enfe);
            }
            em.remove(subjectsEntity);
            em.getTransaction().commit();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public List<SubjectsEntity> findSubjectsEntityEntities() {
        return findSubjectsEntityEntities(true, -1, -1);
    }

    public List<SubjectsEntity> findSubjectsEntityEntities(int maxResults, int firstResult) {
        return findSubjectsEntityEntities(false, maxResults, firstResult);
    }

    private List<SubjectsEntity> findSubjectsEntityEntities(boolean all, int maxResults, int firstResult) {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            cq.select(cq.from(SubjectsEntity.class));
            Query q = em.createQuery(cq);
            if (!all) {
                q.setMaxResults(maxResults);
                q.setFirstResult(firstResult);
            }
            return q.getResultList();
        } finally {
            em.close();
        }
    }

    public SubjectsEntity findSubjectsEntity(int id) {
        EntityManager em = getEntityManager();
        try {
            return em.find(SubjectsEntity.class, id);
        } finally {
            em.close();
        }
    }

    public int getSubjectsEntityCount() {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<SubjectsEntity> rt = cq.from(SubjectsEntity.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
        } finally {
            em.close();
        }
    }
    
}
